[build-system]
requires = ["setuptools>=70.0"]
build-backend = "setuptools.build_meta"

[project]
name = "misc_helper"
version = "0.0.1"
description = "Some small utility to make life easier"
authors = [
  {name = "ComfyUI_MiscHelper", email = "me@sakurakooi.dev"}
]
readme = "README.md"
license = {text = "GNU General Public License v3"}
requires-python = ">=3.10"
classifiers = []
dependencies = [

]


[project.urls]
Repository = "https://github.com/SakuraKoi/ComfyUI_MiscHelper"
BugTracker = "https://github.com/SakuraKoi/ComfyUI_MiscHelper/issues"
Documentation = "https://github.com/SakuraKoi/ComfyUI_MiscHelper/wiki"


[tool.comfy]
PublisherId = "SakuraKoi"
DisplayName = "Misc Helper"
Icon = ""
Tags = []
Repository = "https://github.com/SakuraKoi/ComfyUI_MiscHelper"

includes = []

[tool.setuptools.package-data]
"*" = ["*.*"
